### ISSUE TITLE
Problem with Saving Groudon on [PKHex Plugin] Dynamax Adventure Reset

### ISSUE THREAD

**Issue by jocker1289** [darkfiggy/dmaxplugin#2]
Hey Darkfiggy, 

I have a problem when I want to save Groudon on my last encounter, because if I change the Max Lair Notes to Groudon and then click Apply Selected below, I get this error:

(I have now specially saved it there so as not to blow everything up here ...)

https://pastebin.com/WYX995mM

![Clipboarder 2021 02 13-005](https://user-images.githubusercontent.com/76487487/107851990-1a9c9900-6e0e-11eb-8446-9eb2b5b01456.png)
![Clipboarder 2021 02 13-007](https://user-images.githubusercontent.com/76487487/107851991-1b352f80-6e0e-11eb-898c-5aa37fa8655e.png)
![Clipboarder 2021 02 13-006](https://user-images.githubusercontent.com/76487487/107851992-1bcdc600-6e0e-11eb-9ca7-e2babd5ede0c.png)

When I change this Pokemon to Groudon I always get this error when I go to Apply Seleceted: 
![Clipboarder 2021 02 13-004](https://user-images.githubusercontent.com/76487487/107851993-1d978980-6e0e-11eb-81f5-8da61f849f81.png)

I hope you can start something with this information to help me, thank you;)

**Comment by ReshiQuori** [comment]
Fixed. I just mispelled "Groudon" in the national dex lookup table as "Groundon" lol
